import {
  Activity,
  Ambulance,
  Baby,
  BadgeCheck,
  BriefcaseMedical,
  CalendarDays,
  Camera,
  ClipboardList,
  Clock3,
  Dumbbell,
  Eye,
  FileText,
  FlaskConical,
  HeartPulse,
  Home,
  Hospital,
  Mail,
  MapPin,
  MessageCircle,
  Microscope,
  MonitorUp,
  Phone,
  Pill,
  Printer,
  Radio,
  RefreshCw,
  Route,
  ScanLine,
  Send,
  ShieldAlert,
  Siren,
  Stethoscope,
  Syringe,
  Thermometer,
  Truck,
  UserCheck,
  Video,
  Wifi,
  Wind,
  Zap,
} from 'lucide-react'

const ICONS = {
  activity: Activity,
  ambulance: Ambulance,
  baby: Baby,
  badgeCheck: BadgeCheck,
  briefcaseMedical: BriefcaseMedical,
  calendar: CalendarDays,
  camera: Camera,
  clipboard: ClipboardList,
  clock: Clock3,
  dumbbell: Dumbbell,
  eye: Eye,
  file: FileText,
  flask: FlaskConical,
  heart: HeartPulse,
  home: Home,
  hospital: Hospital,
  mail: Mail,
  mapPin: MapPin,
  message: MessageCircle,
  microscope: Microscope,
  monitor: MonitorUp,
  phone: Phone,
  pill: Pill,
  printer: Printer,
  radio: Radio,
  refresh: RefreshCw,
  route: Route,
  scan: ScanLine,
  send: Send,
  shieldAlert: ShieldAlert,
  siren: Siren,
  stethoscope: Stethoscope,
  syringe: Syringe,
  thermometer: Thermometer,
  truck: Truck,
  userCheck: UserCheck,
  video: Video,
  wifi: Wifi,
  wind: Wind,
  zap: Zap,
}

export default function AppIcon({ name, size = 20, className = '', strokeWidth = 2 }) {
  const Icon = ICONS[name] || Activity
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />
}
